export const MaterialsSubCategories = [
    '💎 Solids',
    '🌳 Wood and Paper',
    '⛱ Soils',
    '⛏ Stone and Minerals',
    '🔩 Metal',
    '💎 Glass and Crystal',
    '🧶 Cloth',
    '🥤 Plastic and Foam',
    '🧤 Rubber',
    '🍮 Gelatinous and Spongy',
    '🕯 Wax',
    '🧊 Ice and Snow',
    '🐱 Hair and Fur',
    ' Other Solids',
    '💧 Liquids',
    '🧪 Non-Newtonian Fluids and Polymers',
    '⚗️ Slime and Putty',
    '🩹 Tape and Adhesives',
    '🧪 Other Non-Newtonian Fluids and Polymers',
    '🌫️ Gasses and Vapors',
    '✨ Powders and Particulates',
    '⚡ Plasma and Energy'
  ]