export const ArtistsSubCategories = [
  '📔⛱ Realism',
  '📔❇ Surrealism',
  '📔🔆 Idealism',
  '📔💮 Abstract',
  '📔🧬 Modernism',
  '📔➿ Post-Impressionism',
  '📔⚜ Art Nouveau',
  '📔🌄 Luminism',
  '📔🦋 Expressionism',
  '📔🔳 Futurism',
  '📔⬛ Gothic',
  '📔☯ Psychedelic',
  '📔🔴 Pop Art',
  '📔🧿 Concept Art',
  '📔❤ Romanticism',
  '📔✡️ Renaissance',
  '📔🌇 Vedute Painting Style',
  '📔🏘 Baroque',
  '📔👁‍🗨 Dadaism',
  '📔👁‍🗨 Neo-Dadaism',
  '📔🖼 Instagram Artist',
  '📔🖼 Artstation Artist',
  '📔🈯 Manga',
  '📔🗿 Non-Painters',
  '📔 Other Artists'
]