export const DrawingAndArtMediums = [
    '✏ Illustration and Drawing',
    '🖼 Drawing Types',
    '✏ Pencil and Graphite',
    '🖊 Ink',
    '🖍 Crayon, Chalk, and Pastel',
    '🎨 Paint',
    '🖼 Painting Types',
    '🎨 Paint Types',
    '🔠 Text',
    '🖨 Printed Art Types',
    '🎲 Physical Mediums',
    '📄 Origami',
    '🀣 Mosaic',
    '🖼 Framed, Banner, and Decal',
    '🗿 Carving, Etching, and Modeling',
    '🏺 Pottery and Glass',
    '🏮 Scrapbooking and Collages',
    '💡 Light',
    '🎲 Other Physical Mediums',
    ' Other'
  ]